export type IconName =
'alarm-fill' |
'alarm'|
'align-bottom'|
'align-center'|
'align-end'|
'align-middle'|
'align-start'|
'align-top'|
'alt'|
'app-indicator'|
'app'|
'archive-fill'|
'archive'|
'arrow90deg-down'|
'arrow90deg-left'|
'arrow90deg-right'|
'arrow90deg-up'|
'arrowbar-down'|
'arrowbar-right'|
'arrowbar-left'|
'arrowbar-up'|
'arrow-clockwise'|
'arrow-counterclockwise'|
'arrowdowncircle-fill'|
'arrowdown-circle'|
'arrowdownleftcircle-fill'|
'arrowdownleft-circle'|
'arrowdownleftsquare-fill'|
'arrowdownleft-square'|
'arrowdown-left'|
'arrowdownrightcircle-fill'|
'arrowdownright-circle'|
'arrowdownrightsquare-fill'|
'arrowdownright-square'|
'arrowdown-right'|
'arrowdown-short'|
'arrowdownsquare-fill'|
'arrowdown-square'|
'arrowdown-up'|
'arrow-down'|
'arrowleftcircle-fill'|
'arrowleft-circle'|
'arrowleft-right'|
'arrowleft-short'|
'arrowleftsquare-fill'|
'arrowleft-square'|
'arrow-left'|
'arrow-repeat'|
'arrowreturn-left'|
'arrowreturn-right'|
'arrowrightcircle-fill'|
'arrowright-circle'|
'arrowright-short'|
'arrowrightsquare-fill'|
'arrowright-square'|
'arrow-right'|
'arrowupcircle-fill'|
'arrowup-circle'|
'arrowupleftcircle-fill'|
'arrowupleft-circle'|
'arrowupleftsquare-fill'|
'arrowupleft-square'|
'arrowup-left'|
'arrowuprightcircle-fill'|
'arrowupright-circle'|
'arrowuprightsquare-fill'|
'arrowupright-square'|
'arrowup-right'|
'arrowup-short'|
'arrowupsquare-fill'|
'arrowup-square'|
'arrow-up'|
'arrowsangle-contract'|
'arrowsangle-expand'|
'arrows-collapse'|
'arrows-expand'|
'arrows-fullscreen'|
'arrows-move'|
'aspectratio-fill'|
'aspect-ratio'|
'asterisk'|
'at'|
'award-fill'|
'award'|
'back'|
'backspace-fill'|
'backspacereverse-fill'|
'backspace-reverse'|
'backspace'|
'badge4k-fill'|
'badge-4k'|
'badge8k-fill'|
'badge-8k'|
'badgead-fill'|
'badge-ad'|
'badgecc-fill'|
'badge-cc'|
'badgehd-fill'|
'badge-hd'|
'badgetm-fill'|
'badge-tm'|
'badgevo-fill'|
'badge-vo'|
'bagcheck-fill'|
'bag-check'|
'bagdash-fill'|
'bag-dash'|
'bag-fill'|
'bagplus-fill'|
'bag-plus'|
'bagx-fill'|
'bag-x'|
'bag'|
'barchart-fill'|
'barchartline-fill'|
'barchart-line'|
'barchart-steps'|
'bar-chart'|
'basket-fill'|
'basket'|
'basket2-fill'|
'basket-2'|
'basket3-fill'|
'basket-3'|
'battery-charging'|
'battery-full'|
'battery-half'|
'battery'|
'bell-fill'|
'bell'|
'bezier'|
'bezier-2'|
'bicycle'|
'binoculars-fill'|
'binoculars'|
'blockquote-left'|
'blockquote-right'|
'book-fill'|
'book-half'|
'book'|
'bookmarkcheck-fill'|
'bookmark-check'|
'bookmarkdash-fill'|
'bookmark-fill'|
'bookmark-dash'|
'bookmarkheart-fill'|
'bookmark-heart'|
'bookmarkplus-fill'|
'bookmark-plus'|
'bookmarkstar-fill'|
'bookmark-star'|
'bookmarkx-fill'|
'bookmark-x'|
'bookmark'|
'bookmarks-fill'|
'bookmarks'|
'bookshelf'|
'bootstrap-fill'|
'bootstrap-reboot'|
'bootstrap'|
'border-style'|
'border-width'|
'boundingbox-circles'|
'bounding-box'|
'boxarrowdown-left'|
'boxarrowdown-right'|
'boxarrow-down'|
'boxarrowindown-left'|
'boxarrowindown-right'|
'boxarrowin-down'|
'boxarrowin-left'|
'boxarrowin-up'|
'boxarrowinup-left'|
'boxarrowinup-right'|
'boxarrow-left'|
'boxarrow-right'|
'boxarrowup-left'|
'boxarrowup-right'|
'boxarrow-up'|
'box'|
'box-seam'|
'braces'|
'bricks'|
'briefcase-fill'|
'briefcase'|
'brightnessalthigh-fill'|
'brightnessaltlow-fill'|
'brightnessalt-low'|
'brightnessalt-high'|
'brightnesshigh-fill'|
'brightness-high'|
'brightnesslow-fill'|
'broadcast-pin'|
'brightness-low'|
'broadcast'|
'brush-fill'|
'brush'|
'bucket-fill'|
'bucket'|
'bug-fill'|
'building'|
'bug'|
'bullseye'|
'calculator'|
'calculator-fill'|
'calendar-check'|
'calendarcheck-fill'|
'calendardate-fill'|
'calendar-date'|
'calendarday-fill'|
'calendar-day'|
'calendarevent-fill'|
'calendar-event'|
'calendar-fill'|
'calendarminus-fill'|
'calendar-minus'|
'calendarmonth-fill'|
'calendar-month'|
'calendarplus-fill'|
'calendar-plus'|
'calendar-range'|
'calendarrange-fill'|
'calendarweek-fill'|
'calendar-week'|
'calendar-x'|
'calendarx-fill'|
'calendar'|
'calendar2check-fill'|
'calendar2-check'|
'calendar2date-fill'|
'calendar2-date'|
'calendar2day-fill'|
'calendar2-day'|
'calendar2event-fill'|
'calendar2-event'|
'calendar2-fill'|
'calendar2minus-fill'|
'calendar2-minus'|
'calendar2month-fill'|
'calendar2-month'|
'calendar2-plus'|
'calendar2plus-fill'|
'calendar2range-fill'|
'calendar2-range'|
'calendar2week-fill'|
'calendar2-week'|
'calendar2x-fill'|
'calendar2-x'|
'calendar-2'|
'calendar3-event'|
'calendar3event-fill'|
'calendar3-fill'|
'calendar3-range'|
'calendar3week-fill'|
'calendar3range-fill'|
'calendar3-week'|
'calendar-3'|
'calendar4-event'|
'calendar4-range'|
'calendar-4'|
'camera-fill'|
'calendar4-week'|
'camerareels-fill'|
'camera-reels'|
'cameravideo-fill'|
'cameravideooff-fill'|
'cameravideo-off'|
'camera'|
'camera-2'|
'camera-video'|
'capslock-fill'|
'capslock'|
'card-checklist'|
'card-heading'|
'card-image'|
'card-text'|
'card-list'|
'caretdown-fill'|
'caretdown-square'|
'caret-down'|
'caretdownsquare-fill'|
'caretleft-fill'|
'caretleftsquare-fill'|
'caretleft-square'|
'caret-left'|
'caretright-fill'|
'caretrightsquare-fill'|
'caretright-square'|
'caretup-fill'|
'caret-right'|
'caretupsquare-fill'|
'caretup-square'|
'caret-up'|
'cartcheck-fill'|
'cart-check'|
'cart-dash'|
'cartdash-fill'|
'cart-fill'|
'cartplus-fill'|
'cartx-fill'|
'cart-plus'|
'cart-x'|
'cart'|
'cart-2'|
'cart-3'|
'cart-4'|
'cash-stack'|
'cast'|
'cash'|
'chatdots-fill'|
'chat-dots'|
'chatleftdots-fill'|
'chat-fill'|
'chatleft-dots'|
'chatleft-fill'|
'chatleftquote-fill'|
'chatleft-quote'|
'chatleft-text'|
'chatlefttext-fill'|
'chat-left'|
'chatquote-fill'|
'chat-quote'|
'chatrightdots-fill'|
'chatright-dots'|
'chatright-fill'|
'chatrightquote-fill'|
'chatright-quote'|
'chatrighttext-fill'|
'chat-right'|
'chatright-text'|
'chatsquaredots-fill'|
'chatsquare-fill'|
'chatsquarequote-fill'|
'chatsquare-dots'|
'chatsquare-quote'|
'chatsquaretext-fill'|
'chatsquare-text'|
'chat-square'|
'chattext-fill'|
'chat-text'|
'chat'|
'checkcircle-fill'|
'check-circle'|
'check-all'|
'checksquare-fill'|
'check-square'|
'check'|
'check2-all'|
'check2-circle'|
'check2-square'|
'check-2'|
'chevronbar-contract'|
'chevronbar-down'|
'chevronbar-expand'|
'chevronbar-left'|
'chevronbar-right'|
'chevronbar-up'|
'chevroncompact-down'|
'chevroncompact-left'|
'chevroncompact-right'|
'chevroncompact-up'|
'chevron-contract'|
'chevrondouble-down'|
'chevrondouble-left'|
'chevrondouble-up'|
'chevron-down'|
'chevrondouble-right'|
'chevron-expand'|
'chevron-left'|
'chevron-right'|
'chevron-up'|
'circle-fill'|
'circle-half'|
'circle-square'|
'circle'|
'clipboard-data'|
'clipboard-check'|
'clipboard-plus'|
'clipboard-x'|
'clipboard-minus'|
'clipboard'|
'clock-history'|
'clock-fill'|
'clock'|
'cloudarrow-down'|
'cloudarrowup-fill'|
'cloudarrowdown-fill'|
'cloudarrow-up'|
'cloudcheck-fill'|
'cloud-check'|
'clouddownload-fill'|
'cloud-download'|
'cloud-fill'|
'cloudminus-fill'|
'cloud-minus'|
'cloudplus-fill'|
'cloud-plus'|
'cloudslash-fill'|
'cloud-slash'|
'cloudupload-fill'|
'cloud-upload'|
'cloud'|
'code-square'|
'code-slash'|
'code'|
'collection-fill'|
'collectionplay-fill'|
'collection-play'|
'collection'|
'columns-gap'|
'columns'|
'command'|
'compass-fill'|
'compass'|
'cone-striped'|
'cone'|
'controller'|
'cpu-fill'|
'cpu'|
'creditcard2back-fill'|
'creditcard2-back'|
'creditcard2front-fill'|
'creditcard2-front'|
'creditcard-fill'|
'credit-card'|
'crop'|
'boxarrowin-right'|
'cup-straw'|
'cup'|
'cursor-fill'|
'cup-fill'|
'cursor-text'|
'dashcircle-fill'|
'cursor'|
'dash-circle'|
'dashsquare-fill'|
'dash-square'|
'dash'|
'diagram2-fill'|
'diagram-2'|
'diagram-3'|
'diagram3-fill'|
'diamond-fill'|
'diamond-half'|
'diamond'|
'dice-1'|
'dice1-fill'|
'dice2-fill'|
'dice-2'|
'dice-3'|
'dice3-fill'|
'dice4-fill'|
'dice-4'|
'dice5-fill'|
'dice-6'|
'dice-5'|
'dice6-fill'|
'display-fill'|
'display'|
'distribute-vertical'|
'doorclosed-fill'|
'distribute-horizontal'|
'door-closed'|
'dooropen-fill'|
'dot'|
'door-open'|
'download'|
'droplet-fill'|
'earbuds'|
'droplet'|
'droplet-half'|
'easel-fill'|
'easel'|
'egg-fried'|
'egg'|
'egg-fill'|
'eject-fill'|
'eject'|
'emojiangry-fill'|
'emoji-angry'|
'emojidizzy-fill'|
'emoji-dizzy'|
'emojiexpressionless-fill'|
'emoji-expressionless'|
'emojifrown-fill'|
'emoji-frown'|
'emojiheart-eyes'|
'emojilaughing-fill'|
'emojihearteyes-fill'|
'emojineutral-fill'|
'emoji-laughing'|
'emojismile-fill'|
'emoji-neutral'|
'emojismileupsidedown-fill'|
'emojismileupside-down'|
'emojisunglasses-fill'|
'emoji-smile'|
'emoji-sunglasses'|
'emojiwink-fill'|
'emoji-wink'|
'envelopeopen-fill'|
'envelope-open'|
'envelope'|
'exclamationcircle-fill'|
'exclamation-circle'|
'exclamationdiamond-fill'|
'exclamation-diamond'|
'exclamationoctagon-fill'|
'exclamation-octagon'|
'exclamationsquare-fill'|
'exclamation-square'|
'exclamation-triangle'|
'exclamation'|
'exclude'|
'eye-fill'|
'eyeslash-fill'|
'eye-slash'|
'envelope-fill'|
'eyeglasses'|
'eye'|
'filearrowdown-fill'|
'filearrow-down'|
'exclamationtriangle-fill'|
'filearrowup-fill'|
'filearrow-up'|
'filebargraph-fill'|
'filebar-graph'|
'filebinary-fill'|
'file-binary'|
'filebreak-fill'|
'file-break'|
'filecheck-fill'|
'file-check'|
'filecode-fill'|
'file-code'|
'filediff-fill'|
'file-diff'|
'fileearmarkarrowdown-fill'|
'fileearmarkarrow-down'|
'fileearmarkarrowup-fill'|
'fileearmarkarrow-up'|
'fileearmarkbargraph-fill'|
'fileearmarkbar-graph'|
'fileearmarkbinary-fill'|
'fileearmark-binary'|
'fileearmarkbreak-fill'|
'fileearmark-break'|
'fileearmarkcheck-fill'|
'fileearmark-check'|
'fileearmarkcode-fill'|
'fileearmarkdiff-fill'|
'fileearmark-code'|
'fileearmark-diff'|
'fileearmarkeasel-fill'|
'fileearmark-easel'|
'fileearmarkexcel-fill'|
'fileearmarkfont-fill'|
'fileearmark-excel'|
'fileearmark-fill'|
'fileearmark-font'|
'fileearmarkimage-fill'|
'fileearmark-image'|
'fileearmarklock-fill'|
'fileearmark-lock'|
'fileearmarklock2-fill'|
'fileearmarklock-2'|
'fileearmarkmedical-fill'|
'fileearmark-medical'|
'fileearmarkminus-fill'|
'fileearmark-minus'|
'fileearmarkmusic-fill'|
'fileearmark-music'|
'fileearmarkperson-fill'|
'fileearmarkplay-fill'|
'fileearmark-person'|
'fileearmark-play'|
'fileearmarkplus-fill'|
'fileearmark-plus'|
'fileearmarkpost-fill'|
'fileearmark-post'|
'fileearmarkppt-fill'|
'fileearmark-richtext'|
'fileearmark-ppt'|
'fileearmarkrichtext-fill'|
'fileearmarkruled-fill'|
'fileearmark-ruled'|
'fileearmarkslides-fill'|
'fileearmark-slides'|
'fileearmarkspreadsheet-fill'|
'fileearmark-spreadsheet'|
'fileearmarktext-fill'|
'fileearmark-text'|
'fileearmarkword-fill'|
'fileearmark-word'|
'fileearmarkx-fill'|
'fileearmark-x'|
'fileearmarkzip-fill'|
'fileearmark-zip'|
'file-earmark'|
'fileeasel-fill'|
'file-easel'|
'fileexcel-fill'|
'filefont-fill'|
'file-fill'|
'file-excel'|
'file-font'|
'fileimage-fill'|
'file-image'|
'file-lock'|
'filelock-fill'|
'filelock2-fill'|
'filelock-2'|
'filemedical-fill'|
'file-medical'|
'fileminus-fill'|
'filemusic-fill'|
'file-minus'|
'file-music'|
'file-person'|
'fileperson-fill'|
'fileplay-fill'|
'file-play'|
'file-plus'|
'fileplus-fill'|
'filepost-fill'|
'fileppt-fill'|
'file-post'|
'file-ppt'|
'filerichtext-fill'|
'file-richtext'|
'fileruled-fill'|
'file-ruled'|
'fileslides-fill'|
'file-slides'|
'filespreadsheet-fill'|
'filetext-fill'|
'file-spreadsheet'|
'file-text'|
'fileword-fill'|
'file-word'|
'filex-fill'|
'file-x'|
'filezip-fill'|
'file-zip'|
'file'|
'files-alt'|
'files'|
'film'|
'filtercircle-fill'|
'filter-left'|
'filter-circle'|
'filter-right'|
'filtersquare-fill'|
'filter-square'|
'filter'|
'flag-fill'|
'flag'|
'flower-1'|
'flower-3'|
'flower-2'|
'folder-check'|
'folder-minus'|
'folder-fill'|
'folder-plus'|
'foldersymlink-fill'|
'folder-symlink'|
'folder-x'|
'folder2-open'|
'folder'|
'folder-2'|
'fonts'|
'forward'|
'forward-fill'|
'front'|
'fullscreen-exit'|
'fullscreen'|
'funnel-fill'|
'funnel'|
'gear-fill'|
'gearwide-connected'|
'gear-wide'|
'gear'|
'gem'|
'geoalt-fill'|
'geo-alt'|
'geo'|
'geo-fill'|
'gift-fill'|
'globe'|
'gift'|
'globe-2'|
'graph-up'|
'graph-down'|
'grid1x2-fill'|
'grid1x-2'|
'grid3x2gap-fill'|
'grid3x2-gap'|
'grid3x-2'|
'grid3x3gap-fill'|
'grid3x3-gap'|
'grid3x-3'|
'grid-fill'|
'grid'|
'grip-horizontal'|
'grip-vertical'|
'hammer'|
'handindex-thumb'|
'handthumbs-down'|
'hand-index'|
'handbag-fill'|
'handthumbs-up'|
'handbag'|
'hash'|
'hdd-fill'|
'hdd-network'|
'hddnetwork-fill'|
'hddrack-fill'|
'hdd-rack'|
'hddstack-fill'|
'hdd-stack'|
'hdd'|
'headphones'|
'headset'|
'heart-fill'|
'heart-half'|
'heart'|
'heptagon-fill'|
'heptagon-half'|
'heptagon'|
'hexagon-fill'|
'hexagon-half'|
'hourglass-bottom'|
'hexagon'|
'hourglass-split'|
'hourglass'|
'hourglass-top'|
'housedoor-fill'|
'house-fill'|
'house'|
'house-door'|
'image-fill'|
'hr'|
'image-alt'|
'image'|
'images'|
'inbox-fill'|
'inbox'|
'inboxes-fill'|
'infocircle-fill'|
'inboxes'|
'info-circle'|
'infosquare-fill'|
'info-square'|
'info'|
'inputcursor-text'|
'input-cursor'|
'intersect'|
'journal-album'|
'journalarrow-down'|
'journalarrow-up'|
'journalbookmark-fill'|
'journal-bookmark'|
'journal-check'|
'journal-medical'|
'journal-code'|
'journal-minus'|
'journal-plus'|
'journal-text'|
'journal-richtext'|
'journal'|
'journal-x'|
'journals'|
'joystick'|
'justify-right'|
'justify'|
'kanban-fill'|
'kanban'|
'key-fill'|
'key'|
'justify-left'|
'keyboard-fill'|
'keyboard'|
'ladder'|
'lamp-fill'|
'lamp'|
'laptop-fill'|
'laptop'|
'layers-half'|
'layers-fill'|
'layoutsidebarinset-reverse'|
'layers'|
'layoutsidebar-inset'|
'layoutsidebar-reverse'|
'layout-split'|
'layout-sidebar'|
'layouttextsidebar-reverse'|
'layouttext-sidebar'|
'layouttextwindow-reverse'|
'layouttext-window'|
'layoutthree-columns'|
'layout-wtf'|
'life-preserver'|
'lightning'|
'lightning-fill'|
'link4-5deg'|
'link'|
'list-check'|
'list-nested'|
'list-stars'|
'list-ol'|
'list-task'|
'list'|
'list-ul'|
'lock-fill'|
'lock'|
'mailbox'|
'mailbox-2'|
'map'|
'map-fill'|
'markdown-fill'|
'markdown'|
'menuapp-fill'|
'menu-app'|
'menubutton-fill'|
'menubutton-wide'|
'menubuttonwide-fill'|
'menu-button'|
'menu-down'|
'menu-up'|
'mic-fill'|
'micmute-fill'|
'mic-mute'|
'mic'|
'minecart-loaded'|
'minecart'|
'moon'|
'mouse'|
'mouse-2'|
'mouse-3'|
'musicnote-beamed'|
'musicnote-list'|
'music-note'|
'music-player'|
'musicplayer-fill'|
'newspaper'|
'node-minus'|
'nodeminus-fill'|
'nodeplus-fill'|
'node-plus'|
'nut'|
'nut-fill'|
'octagon-fill'|
'octagon-half'|
'octagon'|
'outlet'|
'option'|
'paperclip'|
'paragraph'|
'patchcheck-fll'|
'patch-check'|
'patch-exclamation'|
'patchexclamation-fll'|
'patchminus-fll'|
'patch-minus'|
'patchplus-fll'|
'patch-plus'|
'patchquestion-fll'|
'patch-question'|
'pause-fill'|
'pause'|
'peace-fill'|
'peace'|
'pen-fill'|
'pen'|
'pencil-fill'|
'pencil-square'|
'pencil'|
'pentagon-fill'|
'pentagon-half'|
'pentagon'|
'people-fill'|
'percent'|
'people'|
'personbadge-fill'|
'person-badge'|
'personbounding-box'|
'personcheck-fill'|
'person-circle'|
'person-check'|
'persondash-fill'|
'person-dash'|
'person-fill'|
'personlines-fill'|
'personplus-fill'|
'person-plus'|
'person-square'|
'person-x'|
'personx-fill'|
'person'|
'phone-fill'|
'phone-landscape'|
'phonelandscape-fill'|
'phone-vibrate'|
'phone'|
'piechart-fill'|
'pie-chart'|
'pip-fill'|
'pip'|
'play-fill'|
'play'|
'plug-fill'|
'plug'|
'pluscircle-fill'|
'plus-circle'|
'plus-square'|
'plussquare-fill'|
'plus'|
'printer-fill'|
'power'|
'printer'|
'puzzle-fill'|
'puzzle'|
'questiondiamond-fill'|
'questioncircle-fill'|
'question-circle'|
'question-diamond'|
'questionoctagon-fill'|
'question-octagon'|
'questionsquare-fill'|
'question-square'|
'receipt-cutoff'|
'question'|
'receipt'|
'reception-0'|
'reception-1'|
'reception-2'|
'reception-4'|
'reception-3'|
'replyall-fill'|
'reply'|
'reply-fill'|
'rss'|
'scissors'|
'screwdriver'|
'segmented-nav'|
'server'|
'share-fill'|
'share'|
'shield-check'|
'shield-exclamation'|
'shieldfill-check'|
'shieldfill-exclamation'|
'shieldfill-minus'|
'shieldfill-plus'|
'shieldfill-x'|
'shield-fill'|
'shieldlock-fill'|
'shield-lock'|
'shield-minus'|
'shield-plus'|
'shield-shaded'|
'shieldslash-fill'|
'shield-slash'|
'shield-x'|
'shield'|
'shift-fill'|
'shift'|
'shop-window'|
'shop'|
'shuffle'|
'signpost2-fill'|
'signpost-2'|
'signpost-fill'|
'signpostsplit-fill'|
'signpost-split'|
'signpost'|
'sim-fill'|
'sim'|
'skipbackward-fill'|
'skip-backward'|
'skipend-fill'|
'skip-end'|
'skipforward-fill'|
'skip-forward'|
'skipstart-fill'|
'skip-start'|
'slashcircle-fill'|
'slash-circle'|
'slashsquare-fill'|
'slash-square'|
'slash'|
'sliders'|
'smartwatch'|
'sortalphadown-alt'|
'sortalpha-down'|
'sortalphaup-alt'|
'sortalpha-up'|
'sortdown-alt'|
'sort-down'|
'sortnumericdown-alt'|
'sortnumeric-down'|
'sortnumericup-alt'|
'sortnumeric-up'|
'sortup-alt'|
'sort-up'|
'soundwave'|
'speaker-fill'|
'speaker'|
'spellcheck'|
'square-fill'|
'square-half'|
'square'|
'star-fill'|
'star-half'|
'star'|
'stickies-fill'|
'stickies'|
'sticky-fill'|
'sticky'|
'stop-fill'|
'stop'|
'stoplights-fill'|
'stoplights'|
'stopwatch-fill'|
'stopwatch'|
'subtract'|
'suitclub-fill'|
'suit-club'|
'suitdiamond-fill'|
'suit-diamond'|
'suitheart-fill'|
'suit-heart'|
'suitspade-fill'|
'suit-spade'|
'sun'|
'sunglasses'|
'table'|
'tablet-fill'|
'tabletlandscape-fill'|
'tablet-landscape'|
'tablet'|
'tag-fill'|
'tag'|
'tags-fill'|
'tags'|
'telephone-fill'|
'telephoneforward-fill'|
'telephone-forward'|
'telephoneinbound-fill'|
'telephone-inbound'|
'telephoneminus-fill'|
'telephone-minus'|
'telephoneoutbound-fill'|
'telephone-outbound'|
'telephoneplus-fill'|
'telephone-plus'|
'telephonex-fill'|
'telephone-x'|
'telephone'|
'terminal-fill'|
'terminal'|
'text-center'|
'textindent-left'|
'textindent-right'|
'text-left'|
'text-paragraph'|
'text-right'|
'textarea-resize'|
'textarea-t'|
'textarea'|
'thermometer-half'|
'thermometer'|
'threedots-vertical'|
'three-dots'|
'toggle-off'|
'toggle-on'|
'toggle2-off'|
'toggle2-on'|
'toggles'|
'toggles-2'|
'tools'|
'trash-fill'|
'trash'|
'trash2-fill'|
'trash-2'|
'tree-fill'|
'tree'|
'triangle-fill'|
'triangle-half'|
'triangle'|
'trophy-fill'|
'trophy'|
'truck-flatbed'|
'truck'|
'tv-fill'|
'tv'|
'type-bold'|
'typeh-1'|
'typeh-2'|
'typeh-3'|
'type-italic'|
'type-strikethrough'|
'type-underline'|
'type'|
'uichecks-grid'|
'ui-checks'|
'uiradios-grid'|
'ui-radios'|
'union'|
'unlock-fill'|
'unlock'|
'upc-scan'|
'upc'|
'upload'|
'vector-pen'|
'view-list'|
'view-stacked'|
'voicemail'|
'volumedown-fill'|
'volume-down'|
'volumemute-fill'|
'volume-mute'|
'volumeoff-fill'|
'volume-off'|
'volumeup-fill'|
'volume-up'|
'vr'|
'wallet-fill'|
'wallet'|
'wallet-2'|
'watch'|
'wifi-1'|
'wifi-2'|
'wifi-off'|
'wifi'|
'window'|
'wrench'|
'xcircle-fill'|
'x-circle'|
'xdiamond-fill'|
'x-diamond'|
'xoctagon-fill'|
'x-octagon'|
'xsquare-fill'|
'x-square'|
'x'|
'zoom-in'|
'zoom-out'|
'rss-fill'|
'search'|
'reply-all';
